### ISSUE TITLE
Buttons of the forms use the same HTML ID

### ISSUE THREAD

**Issue by scur-iolus** [tiesjan/django-convenient-formsets#10]
The `deleteFormButtonSelector`, `moveFormDownButtonSelector` and the `moveFormUpButtonSelector` in the example provided in the README seem to use the same HTML IDs. In other terms, if a FormSet gathers `N` forms, the `#delete-form-button` CSS selector (for instance) will correspond to `N` elements.

While it does 'work', it's not valid HTML ([see here](https://stackoverflow.com/questions/5611963/can-multiple-different-html-elements-have-the-same-id-if-theyre-different-eleme)) and it can lead to various issues if other parts of the code take for granted that these IDs are unique.

Is there a way to use this extension while avoiding that pitfall?

I suggest to update at least the README.

`django-convenient-formsets` v2.0.

**Comment by tiesjan** [comment]
As per the documentation on the [configuration parameters](https://github.com/tiesjan/django-convenient-formsets#configuration), each of the mentioned selectors are selected _within_ the element found by the `formSelector`. The library will therefore work fine as long as the element identifiers are unique within each form.

Strictly speaking, identical ids will indeed result in invalid HTML. Since you can use any CSS selector, you could go for classes instead. The only constraint is that they are unique in the element hierarchy of a single form.

Although this is all not related to the library and browsers are very lenient in this regard, I have updated the example in b9c54d8 to stick to best practices. Hope this helps. 👍🏻

**Comment by scur-iolus** [comment]
Thank you! I think it's better like this indeed :)
