### ISSUE TITLE
Why is only django 4.2+ supported?

### ISSUE THREAD

**Issue by JhonFrederick** [tiesjan/django-convenient-formsets#9]
Reviewing the implementation that the package has and seeing that the core is mainly javascript, makes me wonder why only support Django 4.2+? Isn't it better to have greater backward compatibility between versions?

This is because currently I would like to use the package in its 2.0 version, but the dependencies cause me problems (I cannot upgrade to Django 4.2 due to other packages). I would consider that if it does not affect the package, modify the dependency with Django 4.2 and indicate that it is compatible with previous versions

**Comment by tiesjan** [comment]
I don't really use this package myself anymore, so I'm maintaining it at best effort. I took a bit of time to modernize and clean-up the code for version 2.0, including the removal of [some backports](https://github.com/tiesjan/django-convenient-formsets/commit/9654547716a8d7cbc5eede569bb087e8820ed0df#diff-2b317264c0ee049f0a473f6f9d58c6f6213338f336d9c7ca1df39c1f643c6679) for older Django versions that I've contributed upstream. Since older Django,  Python and browser versions are also no longer officially supported, I've decided to push the minimum requirements. All of this eases the maintenance of the package.

Feel free to use version 1.2.1 until you've upgraded your Django version. It works perfectly fine, you'll only be missing out on the JavaScript events.

**Comment by CleitonDeLima** [comment]
> I don't really use this package myself anymore

Out of curiosity, why don't you use it anymore? Do you currently work with another stack?

**Comment by tiesjan** [comment]
> Out of curiosity, why don't you use it anymore? Do you currently work with another stack?

Indeed, changed to a job with a different technology stack.

**Comment by JhonFrederick** [comment]
> Feel free to use version 1.2.1 until you've upgraded your Django version. It works perfectly fine, you'll only be missing out on the JavaScript events.
I wanted version 2.0 to have the JavaScript events, but given the above, possibly the best route for me is to fork until I can update Django to version 4.2

**Comment by tiesjan** [comment]
That's probably the best option, yes. By reverting some of the code changes made in 9654547716a8d7cbc5eede569bb087e8820ed0df, you should be able to get it working rather easily. Good luck! 👍🏻
